### ISSUE TITLE
Errors when build on windows

### ISSUE THREAD

**Issue by guillaume-leo** [v7b1/vb.mi-dev#1]
Hey, I'm having an error when I build on windows

Building _____  _____
Reading C:/Users/Guillaume/Documents/vb.mi-dev/package-info.json
CMake Error at source/max-api/script/cmakepp.cmake:20280 (endfunction):
  Flow control statements are not properly nested.
Call Stack (most recent call first):
  source/max-api/script/max-package.cmake:20 (include)
  CMakeLists.txt:12 (include)

-- Configuring incomplete, errors occurred!
See also "C:/Users/Guillaume/Documents/vb.mi-dev/build/CMakeFiles/CMakeOutput.log".

I'm trying to investigate why it happen, but if you have an idea I would not refuse some help.

Thank you 

Guillaume

**Comment by v7b1** [comment]
Hi, the windows side of things here is completely untested and I would be very surprised if it would work right out of the box.
Can't help you with this right now, I'm afraid.
I'm experimenting with github actions right now, and if all goes well there should be automatic builds happening some time in the not so distant future :)

**Comment by guillaume-leo** [comment]
That's super great, Thank you, your work is great :)

**Comment by ABmod** [comment]
actually it does work to some extent, i only compiled few externals i needed, only had to change some mac stuff. i had the same compile errors. seems, that while you installed cmake on windows, in the installer you clicked 'make global path or add path to all users' or smth like that, can't remember now. reinstall cmake, and just don't click anything extra in the installer. let me know if you still have problems

**Comment by v7b1** [comment]
@ABmod great to hear that!

**Comment by guillaume-leo** [comment]
Thank you @ABmod for your answer, can you tell me which mac stuff did you change?
Thank you

**Comment by ABmod** [comment]
don't remember exactly, but i think few constants, accelerate framework, and also 64bit windows dropped inline assembly.

**Comment by guillaume-leo** [comment]
Thank you very much, I will try this

**Comment by ABmod** [comment]
> don't remember exactly, but i think few constants, accelerate framework, and also 64bit windows dropped inline assembly.

actually vs studio 2019 64bit dropped _asm functions, but it is easy to change them

**Comment by guillaume-leo** [comment]
Hey @ABmod, I tried again to build these files without success, do you think you can send the externals with wetransfer? Thank you very much

**Comment by guillaume-leo** [comment]
For the moment I've just achieve to build two of them : vb.mi.mu~ and vb.mi.tds~
For the rest I have a lot of errors, and I don't know what is going on 
![image](https://user-images.githubusercontent.com/77118838/118271843-1ee65a00-b4c2-11eb-9ece-55e7c9bfa1d9.png)

**Comment by v7b1** [comment]
@guillaume-leo here's an experimental windows build of vb.mi.rngs and vb.mi.plts. please try it out and report back.
[https://vboehm.net/xchange/vb.mi-win-2ee8249-release.zip](url)

**Comment by ABmod** [comment]
> Hey @ABmod, I tried again to build these files without success, do you think you can send the externals with wetransfer? Thank you very much

just to clarify, i compiled few externals, and i think dear völker sent both of them. atm have no time for this, but if there is a need, i could compile all of them.

**Comment by guillaume-leo** [comment]
Thank you both of you, I try this right now and @ABmod , I would really like to do it by myself and I don't like the idea of asking someone to do something like this for me. But it's really to complicated for me, so I will wait patiently, for a release one day? I already tried these codes on supercollider and it's awesome.

**Comment by guillaume-leo** [comment]
it's working like a charm. Thank you very much :)

**Comment by v7b1** [comment]
ok, fine - here's the rest to try:
[https://vboehm.net/xchange/vb.mi-objects.zip](https://vboehm.net/xchange/vb.mi-objects.zip)

**Comment by guillaume-leo** [comment]
This is wonderfull, I'm using the scheme for max external to manipulate them. It's working like a charm.

Thank you again Volker :)

**Comment by paradiddle16** [comment]
Hello! I tried the download links for the windows version but to no avail.

**Comment by v7b1** [comment]
Link is updated now, please try again.

**Comment by paradiddle16** [comment]
Wow Thank you very much for taking time to upload this! This seems to have more MI objects than the mac version! That should be in the cycling 74 package manager along with a bunch of your other awesome objects on your website. They are just too good to be enjoyed by a few people! :)
